import "./globals.css";
import React from 'react'; 
import type { Metadata } from "next";
import { ContextHandleProvider } from "../context/contextHandle";

export const metadata: Metadata = {
  title: "Web Map with Earth Engine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextHandleProvider>
        <body>{children}</body>
      </ContextHandleProvider>
    </html>
  );
}
